# Generated by Django 3.2.9 on 2021-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Phrase',
            new_name='Phrase1',
        ),
    ]
