# Generated by Django 3.2.9 on 2021-11-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrase', '0002_auto_20211125_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
